//
// Created by Chris on 10/7/2020.
//

#ifndef LAB07_FILES_SERIALIZATION_CHRISVARSSAL_ARCHIVOMANAGER_H
#define LAB07_FILES_SERIALIZATION_CHRISVARSSAL_ARCHIVOMANAGER_H


class ArchivoManager {

};


#endif //LAB07_FILES_SERIALIZATION_CHRISVARSSAL_ARCHIVOMANAGER_H
